spring:
  devtools:
    restart:
      exclude: static/**
  #  resources:
  #    static-locations: classpath:/static/
  main:
    banner-mode: 'off'
  datasource:
    #    oracle:
    #      url:
    #      username:
    #      password:
    #      driverClassName:
    mysql:
      jdbcUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver


