spring:
  devtools:
    restart:
      exclude: static/**
  #  resources:
  #    static-locations: classpath:/static/
  main:
    banner-mode: 'off'
  datasource:
    oracle:
      jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521/orcl
      username: hxacs0930
      password: hxacs0930
      driverClassName: oracle.jdbc.OracleDriver
#    mysql:
#      jdbcUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#      username: root
#      password: root
#      driverClassName: com.mysql.cj.jdbc.Driver


