spring:
  main:
    banner-mode: 'off'
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
  security:
    user:
      name: admin
      password: admin
server:
  port: 80
