spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  main:
    banner-mode: 'off'
  messages:
    basename: i18n/messages
    encoding: UTF-8
  #  http:
  #    encoding:
  #      charset: utf-8
  thymeleaf:
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
  security:
    user:
      name: admin
      password: admin
remote:
  config: true
  url: localhost:8090/settings
server:
  port: 8090
#  servlet:
#    context-path: "/help"
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO