server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: 123456
  http2:
    enabled: true


spring:
  thymeleaf:
    suffix: .html


custom:
  server:
    http:
      port: 8080