spring:
  devtools:
    restart:
      exclude: static/**
  main:
    banner-mode: 'off'
  datasource:
    oracle:
      jdbcUrl: jdbc:oracle:thin:@192.168.96.142:1521/orcl
      username: datamodel
      password: datamodel
      driverClassName: oracle.jdbc.OracleDriver
#    mysql:
#      jdbcUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#      username: root
#      password: root
#      driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapper/*.xml

