spring:
  main:
    banner-mode: 'off'
  #  datasource:
  #    order:
  #      jdbc-url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8&useSSL=false
  #      username: root
  #      password: root
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #    customer:
  #      jdbc-url: jdbc:mysql://localhost:3306/db2?serverTimezone=GMT%2B8&useSSL=false
  #      username: root
  #      password: root
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  jta:
    atomikos:
      properties:
        enable-logging: false
      datasource:
        one-data:
          unique-resource-name: dataSourceOne
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          xa-properties:
            url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
            user: root
            password: root
        two-data:
          unique-resource-name: dataSourceTwo
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          xa-properties:
            url: jdbc:mysql://localhost:3306/db2?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
            user: root
            password: root

    enabled: true
server:
  port: 8090
