spring:
  main:
    banner-mode: 'off'
  datasource:
    order:
      jdbc-url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    customer:
      jdbc-url: jdbc:mysql://localhost:3306/db2?serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090